### ISSUE TITLE
Get plugin to build in CI

### ISSUE THREAD

**Issue by guysoft** [jenkinsci/configurationslicing-plugin#27]
First issue is to get this plugin building.

I am new to the Jenkins org so please comment if you know something, I might not. 

The last build I see is:
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfigurationslicing-plugin/detail/master/2/pipeline
@oleg-nenashev Is this a failure in the plugin build or the build system itself? I can't see any log indicating what failed on the plugin side of things.

**Comment by guysoft** [comment]
Closing this, moving to Jira bug tracker

**Comment by oleg-nenashev** [comment]
BTW please feel free to disable GitHub Issues in the repo settings if you prefer Jenkins Jira. Right now we do not force Jira or GitHub Issues, p;lugin maintainers are welcome to decide what is better for their projects

**Comment by guysoft** [comment]
@oleg-nenashev For now I'll pick what you are using, because I need your input ;)
